apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: maven-java8
spec:
  containers:
    - name: java8
      image: openjdk:8-jdk
      command:
        - cat
      tty: true
    - name: maven
      image: maven:3.6.3-openjdk-8
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: shared-workspace
          mountPath: /shared
    - name: helm
      image: alpine/helm:3.8.2
      command:
        - cat
      tty: true
    - name: git
      image: alpine/git:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: ssh-key
          mountPath: /ssh-key
          readOnly: true
    - name: aws-cli
      image: amazon/aws-cli
      command:
        - cat
      tty: true
      volumeMounts:
        - name: shared-workspace
          mountPath: /shared
    - name: argocd
      image: quay.io/argoproj/argocd:latest
      command:
        - cat
      tty: true
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: kubeconfig-volume
          mountPath: /home/jenkins/.kube

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
    - name: shared-workspace
      emptyDir: {}
    - name: ssh-key
      secret:
        secretName: jenkins-ssh-key
    - name: ssh-volume 
      emptyDir: {}
    - name: kubeconfig-volume
      secret:
        secretName: jenkins-kubeconfig
        
