apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins-agent: maven-java8
spec:
  containers:
    - name: java8
      image: openjdk:8-jdk
      command:
        - cat
      tty: true
    - name: maven
      image: maven:3.6.3-openjdk-8
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: docker
      image: docker:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: helm
      image: alpine/helm:3.8.2
      command:
        - cat
      tty: true
    - name: git
      image: alpine/git:latest
      command:
        - cat
      tty: true
    - name: aws-cli
      image: amazon/aws-cli
      command:
        - sh
        - -c
        - "apk add --no-cache docker && cat"
      tty: true
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
